/* form_style.js должен быть выполнен перед form_validation.js */
@@include('animation_css_extend.js')
@@include('form_style.js')
@@include('label_animation.js')
@@include('form_validation.js')
@@include('form_mask.js')
@@include('update_svg.js')
@@include('datepicker.js')
@@include('tab_switcher.js')
@@include('visibility_control.js')
/* include('accordion.js')
include('custom_scrollbar.js') */
@@include('range_slider.js')
// include('popups.js')
// include('tooltip.js')
@@include('slick-slider.js')